name: build

on:
  push:
    branches: [ master ]
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '*.md' ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Resume cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-build

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2022-09-14
        target: ${{ matrix.target }}
        components: clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
